### PR TITLE
Fixes transient error

### LINKED ISSUE #15: SystemKey lookup fails at install
Hi 👋 

It seems the following step sometimes fail when the agent isn't fast enough to register the device in jumpcloud:

```
TASK [inviqa.jumpcloud : Look for Jumpcloud System Key] ***************************************************************************
fatal: [ubuntu]: FAILED! => {"changed": true, "cmd": ["grep", "-o", "-P", "(?<=systemKey\\\":\\\")[a-zA-Z0-9]*", "/opt/jc/jcagent.c
onf"], "delta": "0:00:00.013875", "end": "2021-10-08 10:56:03.815038", "msg": "non-zero return code", "rc": 1, "start": "2021-10-08
 10:56:03.801163", "stderr": "", "stderr_lines": [], "stdout": "", "stdout_lines": []}
```

When I relaunch the role it works fine but it's kind of annoying. I'll work on a pull request to fix that by adding a retry loop if that's ok.

### PR DESCRIPTION
**Pull request by ClementGautier**
Fixes #15

### CODE REVIEW

**Comment by ClementGautier** [comment]
I tested the patch multiple times now and it's working pretty well. If you merge this PR could you consider adding the label hacktoberfest-accepted? I need some contribution 😄

**Comment by ClementGautier** [comment]
@marcomc / @scottsb : any chance you could have a look at this PR 🙏?

**Review by marcomc — APPROVED** [review]

**Comment by marcomc** [comment]
> @marcomc / @scottsb : any chance you could have a look at this PR 🙏?

done! sorry for the way, I didn't notice your PR before. accept my apologies

**Comment by ClementGautier** [comment]
@marcomc no worries. Thank you very much!

**Pull request merged**
